server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/telstrainternal
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect